version: '3.1'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - TZ=Asia/Shanghai
    volumes:
      - ./mongo-volume:/data/db

#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    ports:
#      - 58081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_SeERVER: mongodb